In [1]:
import numpy as np

In [2]:
np.empty(2)

array([ 1.44006991e+154, -1.36444519e+292])

In [3]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
x = np.ones(2, dtype=int)
x

array([1, 1])

In [6]:
arr = np.array([2, 1, 5, 7, 3, 8, 6])
np.sort(arr)

array([1, 2, 3, 5, 6, 7, 8])

In [7]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [8]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [9]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [10]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [11]:
a2 = a[None, :]
a2.shape

(1, 6)

In [12]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(a[a < 7])

[1 2 3 4 5 6]


In [14]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [15]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [16]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [17]:
print(a[b])

[1 2 3 4]


In [18]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [19]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [20]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [21]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [22]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [23]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [24]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
b2 = a.copy()
print(b2)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
print(b2.shape)
b2.size

(3, 4)


12

In [29]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [31]:
print(x.shape)
y.shape

(4,)


(5,)

In [36]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [33]:
xx.shape

(4, 1)

In [34]:
y.shape

(5,)

In [38]:
print(xx + y)
(xx + y).shape

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


(4, 5)

In [41]:
print(x.shape)
print(z.shape)

(4,)
(3, 4)


In [42]:
(x + z).shape

(3, 4)

In [43]:
x + z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [44]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, None] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [45]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
               [0.54627315, 0.05093587, 0.40067661, 0.55645993],
               [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [46]:
a.sum()

4.8595784

In [48]:
a.min()

0.05093587

In [49]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [51]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
data.max(axis=0)

array([5, 6])

In [53]:
data.max(axis=1)

array([2, 4, 6])

In [55]:
rng = np.random.default_rng()

In [57]:
rng.integers(5, size=(2, 4))

array([[0, 2, 2, 1],
       [4, 1, 2, 0]], dtype=int64)

In [58]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [59]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [60]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [62]:
unique_values, occurence_count = np.unique(a, return_counts=True)
print(occurence_count)

[3 2 2 2 1 1 1 1 1 1]


In [70]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [71]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [72]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
