**NUMPY COMPUTATION**

In [62]:
import numpy as np

**manipulasi array**

In [63]:
array2d = np.array([[1, 2, 4], [2, 4, 8], [3, 6, 18], [4, 16, 32]])
array3d = np.array([[[.1, .4], [.2, .5], [.3, .6]], [[.7, 1.], [.8, 1.1], [.9, 1.2]]])

print(array2d)
print(array3d)

[[ 1  2  4]
 [ 2  4  8]
 [ 3  6 18]
 [ 4 16 32]]
[[[0.1 0.4]
  [0.2 0.5]
  [0.3 0.6]]

 [[0.7 1. ]
  [0.8 1.1]
  [0.9 1.2]]]


**mengubah dimensi array**

In [64]:
print("old shape:", array2d.shape)
print(array2d)
array2d_new = np.reshape(array2d, (2,6))
print("new shape:", array2d_new.shape)
print(array2d_new)

old shape: (4, 3)
[[ 1  2  4]
 [ 2  4  8]
 [ 3  6 18]
 [ 4 16 32]]
new shape: (2, 6)
[[ 1  2  4  2  4  8]
 [ 3  6 18  4 16 32]]


In [65]:
array2d_new2 = np.reshape(array2d, (3, 2, 2))
print(array2d_new2, array2d_new2.shape)

[[[ 1  2]
  [ 4  2]]

 [[ 4  8]
  [ 3  6]]

 [[18  4]
  [16 32]]] (3, 2, 2)


In [66]:
print("old shape:", array3d.shape)
print(array3d)
array3d_new = np.reshape(array3d, (4, 3))
print("new shape:", array3d_new.shape)
print(array3d_new)

old shape: (2, 3, 2)
[[[0.1 0.4]
  [0.2 0.5]
  [0.3 0.6]]

 [[0.7 1. ]
  [0.8 1.1]
  [0.9 1.2]]]
new shape: (4, 3)
[[0.1 0.4 0.2]
 [0.5 0.3 0.6]
 [0.7 1.  0.8]
 [1.1 0.9 1.2]]


In [67]:
np.transpose(array2d)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 16],
       [ 4,  8, 18, 32]])

In [68]:
np.transpose(array2d, axes=(1, 0))

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 16],
       [ 4,  8, 18, 32]])

In [69]:
np.transpose(array3d)

array([[[0.1, 0.7],
        [0.2, 0.8],
        [0.3, 0.9]],

       [[0.4, 1. ],
        [0.5, 1.1],
        [0.6, 1.2]]])

In [70]:
print(array3d, array3d.shape)

[[[0.1 0.4]
  [0.2 0.5]
  [0.3 0.6]]

 [[0.7 1. ]
  [0.8 1.1]
  [0.9 1.2]]] (2, 3, 2)


In [71]:
test = np.transpose(array3d, axes=(2, 0, 1))

In [72]:
print(test)
print(test.shape)

[[[0.1 0.2 0.3]
  [0.7 0.8 0.9]]

 [[0.4 0.5 0.6]
  [1.  1.1 1.2]]]
(2, 2, 3)


In [73]:
array2d.transpose()

array([[ 1,  2,  3,  4],
       [ 2,  4,  6, 16],
       [ 4,  8, 18, 32]])

In [74]:
array3d.transpose()

array([[[0.1, 0.7],
        [0.2, 0.8],
        [0.3, 0.9]],

       [[0.4, 1. ],
        [0.5, 1.1],
        [0.6, 1.2]]])

In [75]:
array3d.transpose(1, 2, 0)

array([[[0.1, 0.7],
        [0.4, 1. ]],

       [[0.2, 0.8],
        [0.5, 1.1]],

       [[0.3, 0.9],
        [0.6, 1.2]]])

In [76]:
rng = np.random.default_rng(11)

array_131 = rng.integers(10, size=(1, 3, 1))
array_212 = np.array([[[1, 2]], [[1, 2]]])
array_11 = np.array([[10]])
print(array_131, array_131.shape)
print(array_212, array_212.shape)
print(array_11, array_11.shape)

[[[1]
  [1]
  [7]]] (1, 3, 1)
[[[1 2]]

 [[1 2]]] (2, 1, 2)
[[10]] (1, 1)


In [77]:
array_3 = np.squeeze(array_131)
print(array_3, array_3.shape)

array_13 = np.squeeze(array_131, axis=-1)
print(array_13, array_13.shape)

[1 1 7] (3,)
[[1 1 7]] (1, 3)


In [78]:
array_22 = np.squeeze(array_212)
print(array_22, array_22.shape)

[[1 2]
 [1 2]] (2, 2)


In [79]:
np.expand_dims(array2d, axis=1)

array([[[ 1,  2,  4]],

       [[ 2,  4,  8]],

       [[ 3,  6, 18]],

       [[ 4, 16, 32]]])

In [80]:
np.expand_dims(array2d, axis=(1, -1))

array([[[[ 1],
         [ 2],
         [ 4]]],


       [[[ 2],
         [ 4],
         [ 8]]],


       [[[ 3],
         [ 6],
         [18]]],


       [[[ 4],
         [16],
         [32]]]])

In [81]:
array2d[None, :]

array([[[ 1,  2,  4],
        [ 2,  4,  8],
        [ 3,  6, 18],
        [ 4, 16, 32]]])

In [82]:
array2d[:, None, :, None]

array([[[[ 1],
         [ 2],
         [ 4]]],


       [[[ 2],
         [ 4],
         [ 8]]],


       [[[ 3],
         [ 6],
         [18]]],


       [[[ 4],
         [16],
         [32]]]])

In [83]:
fl = array_212.flat
fl[0:4]

array([1, 2, 1, 2])

In [84]:
print(array2d.size)
fl2 = array2d.flat
fl2[0:13]

12


array([ 1,  2,  4,  2,  4,  8,  3,  6, 18,  4, 16, 32])

In [85]:
print(array_212.flatten())
print(array_212.flatten('F'))
print(array_212.flatten('A'))
print(array_212.flatten('K'))

[1 2 1 2]
[1 1 2 2]
[1 2 1 2]
[1 2 1 2]


In [86]:
np.ravel(array_212)

array([1, 2, 1, 2])

**penggabungan array**

In [87]:
x = rng.integers(10, size=(2, 5))
y = rng.integers(10, 20, size=(3, 5))
z = rng.integers(20, 30, size=(3, 3))

print(x, x.shape)
print(y, y.shape)
print(z, z.shape)

[[4 5 6 7 0]
 [4 1 4 9 5]] (2, 5)
[[10 15 11 17 19]
 [19 16 18 13 11]
 [15 14 16 19 12]] (3, 5)
[[28 21 23]
 [27 22 26]
 [24 25 29]] (3, 3)


In [88]:
np.concatenate([x, y])

array([[ 4,  5,  6,  7,  0],
       [ 4,  1,  4,  9,  5],
       [10, 15, 11, 17, 19],
       [19, 16, 18, 13, 11],
       [15, 14, 16, 19, 12]], dtype=int64)

In [89]:
np.concatenate([y, z, y], axis=-1)

array([[10, 15, 11, 17, 19, 28, 21, 23, 10, 15, 11, 17, 19],
       [19, 16, 18, 13, 11, 27, 22, 26, 19, 16, 18, 13, 11],
       [15, 14, 16, 19, 12, 24, 25, 29, 15, 14, 16, 19, 12]], dtype=int64)

In [90]:
np.concatenate([np.resize(x, (5,3)), z])

array([[ 4,  5,  6],
       [ 7,  0,  4],
       [ 1,  4,  9],
       [ 5,  4,  5],
       [ 6,  7,  0],
       [28, 21, 23],
       [27, 22, 26],
       [24, 25, 29]], dtype=int64)

In [91]:
np.append(y, ([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]), axis=0)

array([[10, 15, 11, 17, 19],
       [19, 16, 18, 13, 11],
       [15, 14, 16, 19, 12],
       [ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5]], dtype=int64)

In [92]:
a_try = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b_try = np.array([[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])

In [93]:
np.hstack((a_try, b_try))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [94]:
c_try = np.array([[[1], [2], [3]], [[4], [5], [6]]])
d_try = np.array([[[7], [8], [9]], [[10], [11], [12]]])
print(c_try)
print(d_try)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [95]:
np.hstack((d_try, c_try))

array([[[ 7],
        [ 8],
        [ 9],
        [ 1],
        [ 2],
        [ 3]],

       [[10],
        [11],
        [12],
        [ 4],
        [ 5],
        [ 6]]])

In [96]:
np.vstack((a_try, b_try))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [97]:
np.vstack((d_try, c_try))

array([[[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]]])

Tugas Eksplorasi

1. Perbedaan np.append, np.hstack, np.vstack

jika *np.append*, menambahkan array baru pada array yg dituju, bila axis tidak diisi maka defaultnya adalah axis 0. sehingga, penambahan array akan dilakukan ke axis 0 (baris baru). pada append, size array harus sama pada axis antara yg akan ditambahkan dan yg akan dituju. dimensi juga harus sama.

jika *np.hstack*, menggabungkan array baru pada array yg dituju secara horizontal (kolom baru). dimensi harus sama. size baris jg harus sama.

jika *np.vstack*, menggabungkan array baru pada array yg dituju secara vertikal (baris baru). dimensi harus sama. size kolom harus sama

2. Perbedaan np.hstack, np.vstack, np.concatenate

*np.concatenate* = Join a sequence of arrays along an existing axis

*np.hstack* = Stack arrays in sequence horizontally (column wise)

*np.vstack* = Stack arrays in sequence vertically (row wise)

In [98]:
print(x)
print(y)
print(z)
np.append(x, y)

[[4 5 6 7 0]
 [4 1 4 9 5]]
[[10 15 11 17 19]
 [19 16 18 13 11]
 [15 14 16 19 12]]
[[28 21 23]
 [27 22 26]
 [24 25 29]]


array([ 4,  5,  6,  7,  0,  4,  1,  4,  9,  5, 10, 15, 11, 17, 19, 19, 16,
       18, 13, 11, 15, 14, 16, 19, 12], dtype=int64)

In [99]:
np.append(y, z)

array([10, 15, 11, 17, 19, 19, 16, 18, 13, 11, 15, 14, 16, 19, 12, 28, 21,
       23, 27, 22, 26, 24, 25, 29], dtype=int64)

In [100]:
np.append(y, z, axis=1)

array([[10, 15, 11, 17, 19, 28, 21, 23],
       [19, 16, 18, 13, 11, 27, 22, 26],
       [15, 14, 16, 19, 12, 24, 25, 29]], dtype=int64)

In [101]:
np.append(x, y, axis=0)

array([[ 4,  5,  6,  7,  0],
       [ 4,  1,  4,  9,  5],
       [10, 15, 11, 17, 19],
       [19, 16, 18, 13, 11],
       [15, 14, 16, 19, 12]], dtype=int64)

In [102]:
np.hstack((y, z))

array([[10, 15, 11, 17, 19, 28, 21, 23],
       [19, 16, 18, 13, 11, 27, 22, 26],
       [15, 14, 16, 19, 12, 24, 25, 29]], dtype=int64)

In [103]:
np.vstack((x, y))

array([[ 4,  5,  6,  7,  0],
       [ 4,  1,  4,  9,  5],
       [10, 15, 11, 17, 19],
       [19, 16, 18, 13, 11],
       [15, 14, 16, 19, 12]], dtype=int64)

**Operasi aritmatika dengan numpy**

In [104]:
a = 2
b = 1.5
c = 10

x = np.array([5, 10, 15])
y = x[None, :]
z = x[:, None]

print(x.shape)
print(y.shape)
print(z.shape)

(3,)
(1, 3)
(3, 1)


In [105]:
print(x)
print(y)
print(z)

[ 5 10 15]
[[ 5 10 15]]
[[ 5]
 [10]
 [15]]


In [106]:
print(x + a)
print(y + b)
print(z + c)

[ 7 12 17]
[[ 6.5 11.5 16.5]]
[[15]
 [20]
 [25]]


In [107]:
x + x

array([10, 20, 30])

In [108]:
x + y

array([[10, 20, 30]])

In [109]:
x + z

array([[10, 15, 20],
       [15, 20, 25],
       [20, 25, 30]])

In [110]:
y + z

array([[10, 15, 20],
       [15, 20, 25],
       [20, 25, 30]])

In [111]:
xx = np.resize(x, (4, x.shape[0]))
print(xx.shape)
print(xx.size)
print(xx)

(4, 3)
12
[[ 5 10 15]
 [ 5 10 15]
 [ 5 10 15]
 [ 5 10 15]]


In [112]:
x + xx

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [113]:
xx + y

array([[10, 20, 30],
       [10, 20, 30],
       [10, 20, 30],
       [10, 20, 30]])

In [114]:
print(xx[:, None])
print(xx[:, None].shape)
print(xx[:, None].size)

[[[ 5 10 15]]

 [[ 5 10 15]]

 [[ 5 10 15]]

 [[ 5 10 15]]]
(4, 1, 3)
12


In [115]:
print(z, z.shape, z.size)

[[ 5]
 [10]
 [15]] (3, 1) 3


In [116]:
xx + z

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [117]:
xx[:, None] + z

array([[[10, 15, 20],
        [15, 20, 25],
        [20, 25, 30]],

       [[10, 15, 20],
        [15, 20, 25],
        [20, 25, 30]],

       [[10, 15, 20],
        [15, 20, 25],
        [20, 25, 30]],

       [[10, 15, 20],
        [15, 20, 25],
        [20, 25, 30]]])

KUIS

xx + z tidak bisa dijalankan karena vektornya ataupun matriksnya berbeda, untuk xx vektornya adalah 4 dan axis 3, sedangkan z vektor 3 dan axis 1
sedangkan untuk xx[:, None] + z, terdapat matriks yang sama yaitu 1, 3 dengan 3, 1

**Perkalian**

In [118]:
d = 10
print(x * d)
print(y * d)
print(z * d)
print(xx * d)
print(array3d * d)

[ 50 100 150]
[[ 50 100 150]]
[[ 50]
 [100]
 [150]]
[[ 50 100 150]
 [ 50 100 150]
 [ 50 100 150]
 [ 50 100 150]]
[[[ 1.  4.]
  [ 2.  5.]
  [ 3.  6.]]

 [[ 7. 10.]
  [ 8. 11.]
  [ 9. 12.]]]


In [119]:
print(np.multiply(x, d))
print(np.multiply(xx, d))

[ 50 100 150]
[[ 50 100 150]
 [ 50 100 150]
 [ 50 100 150]
 [ 50 100 150]]


In [120]:
print(np.multiply(xx, y))
print(np.multiply(y, z))

[[ 25 100 225]
 [ 25 100 225]
 [ 25 100 225]
 [ 25 100 225]]
[[ 25  50  75]
 [ 50 100 150]
 [ 75 150 225]]


In [121]:
np.dot(xx, xx.T)

array([[350, 350, 350, 350],
       [350, 350, 350, 350],
       [350, 350, 350, 350],
       [350, 350, 350, 350]])

In [122]:
np.dot(y, z)

array([[350]])

In [123]:
np.dot(z, y)

array([[ 25,  50,  75],
       [ 50, 100, 150],
       [ 75, 150, 225]])