NUMPY ARRAY

**Menyiapkan NUMPY**

In [1]:
import numpy as np
print(np.__version__)

1.21.2


**Vektor, array 1-dimensi**

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
int_array = np.array([1, 2, 3])

In [4]:
array_0 = np.array([0, 0, 0, 0, 0])
print(array_0)
print(array_0.size)

[0 0 0 0 0]
5


In [5]:
array_even = np.array([2, 4, 6, 8, 10])
print(array_even)
print(array_even.size)

[ 2  4  6  8 10]
5


**Matriks, Array 2-Dimensi**

In [6]:
array_2x2 = np.array([[1, 2], [3, 4]])
array_1x2 = np.array([[5, 5]])
array_2x1 = np.array([[2], [4]])

print(array_2x2)
print(array_1x2)
print(array_2x1)

[[1 2]
 [3 4]]
[[5 5]]
[[2]
 [4]]


**Array N-Dimensi**

In [7]:
array_4d = np.array([[[[1, 2, 1], [3, 4, 3]], [[5, 6, 5], [7, 8, 7]]], [[[12, 13, 12], [11, 12, 11]], [[13, 14, 13], [15, 16, 15]]]])

KUIS

In [8]:
array_quiz1 = np.array([[[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3], [1, 2, 3]]])
print(array_quiz1)
print(array_quiz1.shape)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
(3, 3, 3)


In [9]:
array_quiz2 = np.array([[[4, 5, 6, 7]], [[4, 5, 6, 7]]])
print(array_quiz2)
print(array_quiz2.shape)

[[[4 5 6 7]]

 [[4 5 6 7]]]
(2, 1, 4)


In [10]:
array_quiz3 = np.array([[[[[8], [9]]], [[[8], [9]]]], [[[[8], [9]]], [[[8], [9]]]]])
print(array_quiz3)
print(array_quiz3.shape)

[[[[[8]
    [9]]]


  [[[8]
    [9]]]]



 [[[[8]
    [9]]]


  [[[8]
    [9]]]]]
(2, 2, 1, 2, 1)


**Penciptaan Array**

**np.linspace dan np.arange**

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(1, 10, dtype=float)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(0, 11, 2)

In [ ]:
np.arange(10, 0, -1)

In [ ]:
np.arange(0, 10, -1)

In [16]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
np.linspace(0, 100, 50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

**np.eye**

In [18]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
print(np.eye(4, 6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [20]:
array_tril = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [21]:
array_explore = np.tri(4, 6, 1)

In [22]:
print(np.tril([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]))

[[1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


In [23]:
print(array_explore)

[[1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]]


In [24]:
print(np.tril(array_explore))

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [25]:
print(np.triu([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]))

[[1 2 3 4 5]
 [0 2 3 4 5]
 [0 0 3 4 5]
 [0 0 0 4 5]]


**Array Nol, Satuan, Acak**

In [26]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [27]:
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
print(np.zeros((3, 2, 1)))

[[[0.]
  [0.]]

 [[0.]
  [0.]]

 [[0.]
  [0.]]]


In [29]:
print(np.ones((5, 4, 3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [30]:
rng = np.random.default_rng()

print(rng, type(rng))

Generator(PCG64) <class 'numpy.random._generator.Generator'>


In [31]:
print(rng.standard_normal(5))

[0.55475648 2.01378982 0.12921374 0.31151894 0.69908221]


In [32]:
print(rng.standard_normal(size=(3, 3)))

[[ 0.33513133  0.44065422 -0.58175418]
 [-1.80357449 -1.05905086 -0.48752912]
 [-0.16034145  1.81492215 -0.62553774]]


In [33]:
print(rng.integers(5, 10, size=10))

[5 9 8 9 8 5 6 8 9 6]


In [34]:
print(rng.uniform(size=(2, 5)))

[[0.66998541 0.91746161 0.43647626 0.86203407 0.29052047]
 [0.02074079 0.08491057 0.96934419 0.67710892 0.54359491]]


In [35]:
print(rng.uniform(0, 10, size=(1, 6)))

[[8.55143741 3.80309543 0.81621002 4.51096983 5.4505784  2.90602149]]


In [36]:
rng_with_seed = np.random.default_rng(111)

print(rng_with_seed, type(rng_with_seed))

Generator(PCG64) <class 'numpy.random._generator.Generator'>


In [37]:
rng_with_seed = np.random.default_rng(111)

print(rng_with_seed.integers(5, 10, size=(10)))

[7 5 8 5 8 7 6 8 9 8]


In [38]:
rng_with_seed = np.random.default_rng(111)

print(rng_with_seed.integers(5, 10, size=(12)))

[7 5 8 5 8 7 6 8 9 8 8 5]


**Indexing, Slicing, dan Perulangan**

In [39]:
print("array:", int_array)
print(int_array[2])
print(int_array[-2])
print(int_array[:2])

array: [1 2 3]
3
2
[1 2]


In [40]:
print("array 2D:", array_2x2)
print(array_2x2[0, 1])
print(array_2x2[:, 0])
print(array_2x2[1])

array 2D: [[1 2]
 [3 4]]
2
[1 3]
[3 4]


In [41]:
print(array_4d, array_4d.shape)
print("-------------------")
print(array_4d[0])
print("-------------------")
print(array_4d[0, 0])
print("-------------------")
print(array_4d[1, :, 1, :])
print("-------------------")
print(array_4d[:, :, :, 0])

[[[[ 1  2  1]
   [ 3  4  3]]

  [[ 5  6  5]
   [ 7  8  7]]]


 [[[12 13 12]
   [11 12 11]]

  [[13 14 13]
   [15 16 15]]]] (2, 2, 2, 3)
-------------------
[[[1 2 1]
  [3 4 3]]

 [[5 6 5]
  [7 8 7]]]
-------------------
[[1 2 1]
 [3 4 3]]
-------------------
[[11 12 11]
 [15 16 15]]
-------------------
[[[ 1  3]
  [ 5  7]]

 [[12 11]
  [13 15]]]
