**DESCRIPTIVE STATISTICS**

**Data**

KUIS

|Student Name| |Asignment| |Quiz| |Exam|
|------------| |---------| |----| |----|
|Student X| |70| |85| |85|

**Jenis Data**

Kuis

variable **group, treatment, control** is *categorical* *nominal* variable. **ct** is a *numerical* *discrete* variable

**Ukuran Pemusatan Data**

**Rata-Rata (Mean)**

In [1]:
num_friends = [100.0, 49, 41, 40, 25, 21, 21, 19, 19, 18, 18, 16, 15, 15, 15, 15,
               14, 14, 13, 13, 13, 13, 12, 12 , 11, 10, 10, 10, 10 ,10, 10, 10, 10,
               10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
               9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7,
               7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
               6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4,
               4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 1, 1, 1]

In [2]:
print(num_friends)

[100.0, 49, 41, 40, 25, 21, 21, 19, 19, 18, 18, 16, 15, 15, 15, 15, 14, 14, 13, 13, 13, 13, 12, 12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [3]:
def mean(data):
    """Calculate mean of data"""
    return sum(data) / len(data)

KUIS

In [4]:
print("Mean of number of friends of users:", mean(num_friends))

Mean of number of friends of users: 7.333333333333333


In [5]:
import numpy as np

In [6]:
np.mean(num_friends)

7.333333333333333

**Nilai Tengah (Median)**

In [7]:
len(num_friends)

204

In [19]:
def median(data):
    """Return median value of data. Return list of axis=0 if it has more than 1-D array"""
    data = sorted(data)
    if len(data) % 2 == 0:
        lower_bound = len(data) // 2 - 1
        upper_bound = len(data) // 2
        return ((data[lower_bound]) + (data[upper_bound])) / 2
    return data[(len(data) // 2)]

In [9]:
a = int(len(num_friends) / 2)
b = int((len(num_friends) / 2) + 1)
print(a, b)
print(num_friends[a+1])
print(num_friends[b+1])
print(((num_friends[a+1]) + (num_friends[b+1])) / 2)

102 103
6
6
6.0


In [10]:
test = [1, 2, 3, 4]

In [11]:
len(test) // 2

2

In [20]:
median(test)

2.5

In [13]:
median(num_friends)

6.0

In [14]:
np.median(num_friends)

6.0

In [15]:
median(num_friends) == np.median(num_friends)

True

In [16]:
num_friends_2 = np.array([
    [100.0, 49, 41],
    [14, 14, 13],
    [10, 10, 10],
    [9, 9, 9],
    [7, 7, 7],
    [6, 6, 4],
    [4, 4, 3],
    [3, 3, 2],
    [2, 2, 1],
    [2, 2, 1]
])

In [17]:
np.median(num_friends_2, axis=0)

array([6.5, 6.5, 5.5])

In [21]:
median(num_friends_2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
a = int(len(num_friends_2) / 2)
b = int((len(num_friends_2) / 2) + 1)
print(a, b)
((num_friends_2[a+1]) + (num_friends_2[b])) / 2
print(num_friends_2[a])
print(num_friends_2[b])

5 6
[6. 6. 4.]
[4. 4. 3.]


**Modus (Mode)**

In [23]:
def mode(x):
    """Return a list of most-frequent values in x, might be more than one."""
    counts = {
        value: x.count(value)
        for value in set(x)
    }
    max_count = max(counts.values())
    return [
        (v, c) for v, c in counts.items()
        if c == max_count
    ]

In [24]:
print(num_friends)

[100.0, 49, 41, 40, 25, 21, 21, 19, 19, 18, 18, 16, 15, 15, 15, 15, 14, 14, 13, 13, 13, 13, 12, 12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [25]:
mode(num_friends)

[(1, 22), (6, 22)]

In [26]:
import scipy.stats

In [27]:
print(num_friends_2)

[[100.  49.  41.]
 [ 14.  14.  13.]
 [ 10.  10.  10.]
 [  9.   9.   9.]
 [  7.   7.   7.]
 [  6.   6.   4.]
 [  4.   4.   3.]
 [  3.   3.   2.]
 [  2.   2.   1.]
 [  2.   2.   1.]]


In [28]:
mode_num_friends = scipy.stats.mode(num_friends)
mode_num_friends2 = scipy.stats.mode(num_friends_2)
print(mode_num_friends)
print(mode_num_friends2)
print(mode_num_friends.mode, mode_num_friends.count)
print(mode_num_friends2.mode, mode_num_friends2.count)

ModeResult(mode=array([1.]), count=array([22]))
ModeResult(mode=array([[2., 2., 1.]]), count=array([[2, 2, 2]]))
[1.] [22]
[[2. 2. 1.]] [[2 2 2]]


In [29]:
#pertanyaan: itu kan modenya harusnya ada 1 dan 6, tp yg muncul hanya 1. apakah itu akan berpengaruh nantinya? bagaimana cara agar yg muncul 2?

In [30]:
mode_num_friends2 = scipy.stats.mode(num_friends_2, axis=1)
print(mode_num_friends2)
print()
print(mode_num_friends2.mode, mode_num_friends2.count)

ModeResult(mode=array([[41.],
       [14.],
       [10.],
       [ 9.],
       [ 7.],
       [ 6.],
       [ 4.],
       [ 3.],
       [ 2.],
       [ 2.]]), count=array([[1],
       [2],
       [3],
       [3],
       [3],
       [2],
       [2],
       [2],
       [2],
       [2]]))

[[41.]
 [14.]
 [10.]
 [ 9.]
 [ 7.]
 [ 6.]
 [ 4.]
 [ 3.]
 [ 2.]
 [ 2.]] [[1]
 [2]
 [3]
 [3]
 [3]
 [2]
 [2]
 [2]
 [2]
 [2]]


**Ukuran Persebaran Data**

**Kuantil (Quantile)**

In [31]:
print(num_friends)

[100.0, 49, 41, 40, 25, 21, 21, 19, 19, 18, 18, 16, 15, 15, 15, 15, 14, 14, 13, 13, 13, 13, 12, 12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [32]:
np.quantile(num_friends, .5) == np.median(num_friends)

True

In [33]:
print(np.quantile(num_friends, .5))
print(np.median(num_friends))

6.0
6.0


In [34]:
print(np.quantile(num_friends, .25))
print(np.percentile(num_friends, 25))

3.0
3.0


In [35]:
print(np.quantile(num_friends, [.25, .5, .75]))
print(np.percentile(num_friends, [25, 50, 75]))

[3. 6. 9.]
[3. 6. 9.]


In [36]:
test = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [37]:
print(np.quantile(test, [0., .1, .25, .4, .5, .75, 1.]))

[ 1.   2.8  5.5  8.2 10.  14.5 19. ]


In [38]:
test2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

In [39]:
print(np.quantile(test2, [0, .1, .25, .4, .5, .75, 1]))

[ 1.    2.7   5.25  7.8   9.5  13.75 18.  ]


In [40]:
def quantile(data, q):
    """Return q-th quantile of the data.
    data = array like object
    q = quantile to compute, between 0 and 1 inclusive"""
    data = sorted(data)
    if q < 0 or q > 1: #check if q is between 0 and 1
        return "ValueError. q must be between 0 and 1 inclusive"
    ith_observation = q * (len(data) + 1)
    if type(ith_observation) == int: #if ith_observation integer number
        return [data[ith_observation]]
    if type(ith_observation) == float: #if ith_observation folat number
        value_1 = data[int(ith_observation - 1)]
        value_2 = data[int(ith_observation)]
        if value_1 == value_2:
            return [value_1]
        return [value_1 + (value_2 - value_1) * (ith_observation - int(ith_observation))]

In [41]:
quantile(test2, .25)

[4.75]

**Jangkauan (Range)**

In [42]:
def data_range(x):
    return max(x) - min(x)

In [43]:
data_range(num_friends)

99.0

In [44]:
np.ptp(num_friends)

99.0

**Varian (Variance)**

In [45]:
print(num_friends)

[100.0, 49, 41, 40, 25, 21, 21, 19, 19, 18, 18, 16, 15, 15, 15, 15, 14, 14, 13, 13, 13, 13, 12, 12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [46]:
np.var(num_friends, ddof=1)

81.54351395730707

KUIS

In [47]:
def sum_of_squares(x):
    return sum([item**2 for item in x])

def deviation_mean(x):
    mean = sum(x) / len(x)
    return [item - mean for item in x]

def variance(x):
    return sum_of_squares(deviation_mean(x)) / (len(x) - 1)

In [48]:
test_var = [1, 2, 3, 4]

In [49]:
sum_of_squares(test_var)

30

In [50]:
print(sum_of_squares(test_var))
deviation_mean(test_var)

30


[-1.5, -0.5, 0.5, 1.5]

In [51]:
variance(test_var)

1.6666666666666667

In [52]:
np.var(test_var, ddof=1)

1.6666666666666667

In [53]:
print(variance(np.array(num_friends)))
print(np.var(num_friends, ddof=1))

81.54351395730716
81.54351395730707


In [54]:
#pertanyaan: gimana caranya biar bisa pake list?

**Standar Deviasi (Standard Deviation)**

In [55]:
def standard_deviation(x):
    return variance(x)**(1/2)

In [56]:
np.std(num_friends, ddof=1)

9.030144736232474

In [57]:
standard_deviation(np.array(num_friends))

9.03014473623248

Jangkauan Interkuartil (interquartile Range)

In [58]:
q1, q3 = np.quantile(num_friends, [.25, .75])
IQR = q3 - q1

print(q1)
print(q3)
print(IQR)

3.0
9.0
6.0


**Kovariansi (Covariance) dan Korelasi (Correlation)**

In [59]:
some_friends = num_friends[::-1]
print(num_friends)
print(some_friends)

[100.0, 49, 41, 40, 25, 21, 21, 19, 19, 18, 18, 16, 15, 15, 15, 15, 14, 14, 13, 13, 13, 13, 12, 12, 11, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6

In [60]:
np.cov(num_friends, some_friends, ddof=1)

array([[ 81.54351396, -26.59441708],
       [-26.59441708,  81.54351396]])

KUIS

In [61]:
def covariance(data1, data2):
    return sum((data1 - (sum(data1) / len(data1))) * (data2 - (sum(data2) / len(data2)))) / (len(data1) - 1)

In [62]:
covariance(np.array(num_friends), np.array(some_friends))

-26.594417077175624

In [63]:
#apakah benar?

In [64]:
np.corrcoef(num_friends, some_friends)

array([[ 1.        , -0.32613774],
       [-0.32613774,  1.        ]])

In [65]:
def correlation(data1, data2):
    return covariance(data1, data2) / (standard_deviation(data1) * standard_deviation(data2))

In [66]:
correlation(np.array(num_friends), np.array(some_friends))

-0.32613773660893963